sudo: required
language: go
services:
  - docker

env: GO111MODULE=on

before_install:
  # Install google cli and kubectl
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl

  # Authorize google cli
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in build/assets/service-account.json.enc -out build/assets/service-account.json -d
  - gcloud auth active-service-account --key-file service-account.json

  # Config project settings
  - gcloud config set project fib-overkill
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials fib-overkill-cluser

  # Log into dockhub using travis env var
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Build dev docker image for testing
  - docker build -t dnilosek/fib-overkill-web-test -f ./web/dockerfile.dev ./web

script:
  # Run tests
  - docker run -e CI=true dnilosek/fib-overkill-web-test npm test
  - make dep && make test

deploy:
  provider: script
  script: bash ./build/travis/deploy.sh
  on:
    branch: master
