sudo: required
language: go
services:
  - docker

env: GO111MODULE=on

before_install:
  - docker build -t dnilosek/fib-overkill-web-test -f ./web/dockerfile.dev ./web
  
script:
  - docker run -e CI=true dnilosek/fib-overkill-web-test npm test 
  - make dep && make test

after_success:
