sudo: required
language: go
services:
  - docker

env: GO111MODULE=on

before_install:
  - docker build -t dnilosek/fib-overkill-web-test -f ./web/dockerfile.dev ./web
  
script:
  - docker run -e CI=true dnilosek/fib-overkill-web-test npm test 
  - make dep && make test

after_success:
  - make build
  - docker build -t dnilosek/fib-overkill-api -f api/dockerfile .
  - docker build -t dnilosek/fib-overkill-worker -f worker/dockerfile .
  - docker build -t dnilosek/fib-overkill-web ./web
  - docker build -t dnilosek/fib-overkill-nginx ./nginx

  # Log to dockerhub and push up images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dnilosek/fib-overkill-api
  - docker push dnilosek/fib-overkill-worker
  - docker push dnilosek/fib-overkill-web
  - docker push dnilosek/fib-overkill-nginx 
