sudo: required
language: go
services:
  - docker

env: GO111MODULE=on GOFLAGS='-mod vendor'

before_install:
  - docker build -t dnilosek/fib-overkill-web-test -f ./web/dockerfile.dev ./
  
script:
  - docker run -e CI=true dnilosek/fib-overkill-web-test npm test 
  - make test

after_success:
