version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    build:
      dockerfile: dockerfile
      context: ./nginx
    restart: always
    ports:
      - '8080:80'
  web:
    build:
      dockerfile: dockerfile.dev
      context: ./web
    volumes:
      - /app/node_modules
      - ./web:/app:z
  api:
    build:
      dockerfile: api/dockerfile
      context: ./
    depends_on:
      - postgres
      - redis
    environment:
      - API_PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    build:
      dockerfile: worker/dockerfile
      context: ./
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
